services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongodb_data:/data/db
    env_file: .env

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file: .env
    depends_on:
      - mongo

  graphql:
    image: graphql
    build:
      context: packages/graphql
      dockerfile: Dockerfile
      target: prod
    command: node ./__build__/index.js
    restart: always
    volumes:
      - ./packages/graphql/src:/usr/src/app/src
    ports:
      - 3001:3001
    env_file: .env
    environment:
      PORT: 3001
    depends_on:
      - mongo

  web:
    image: web
    build:
      context: packages/web
      dockerfile: Dockerfile
      target: prod
    command: node __sapper__/build
    restart: always
    volumes:
      - ./packages/web/src:/usr/src/app/src
      - ./packages/web/static:/usr/src/app/static
    ports:
      - 3000:3000
      - 10000:10000
    depends_on:
      - graphql

volumes:
  mongodb_data:
